# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('locationID', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
