# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminUser', '0003_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20161225_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('staffID', models.AutoField(primary_key=True, serialize=False)),
                ('dateOfBirth', models.DateField()),
                ('nationality', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=6)),
                ('designation', models.CharField(choices=[(b'Admin', b'Admin'), (b'Project Manager', b'Project Manager'), (b'Employee', b'Employee')], max_length=15)),
                ('workStatus', models.CharField(max_length=50)),
                ('skillLevel', models.IntegerField()),
                ('preferredLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUser.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
