# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161226_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
