# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0003_location'),
        ('accounts', '0007_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminUser.location'),
            preserve_default=False,
        ),
    ]
