# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_projects_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projectManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.profile'),
        ),
    ]
