# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20161227_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectswithskills',
            name='hoursRequired',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffwithskills',
            name='hoursAvailable',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
