# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20161227_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('holidayID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
    ]
