# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='seenDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
