# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170104_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.holidays'),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.projects'),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.profile'),
        ),
    ]
