# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alerts_fromstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='fromStaff',
        ),
    ]
