# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='fromStaff',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='project',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='holidays',
            name='staffID',
        ),
        migrations.DeleteModel(
            name='alerts',
        ),
        migrations.DeleteModel(
            name='holidays',
        ),
    ]
