# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20170107_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('alertID', models.AutoField(primary_key=True, serialize=False)),
                ('alertType', models.CharField(choices=[(b'Project', b'Project'), (b'Leave', b'Leave'), (b'Staff', b'Staff')], max_length=30)),
                ('alertDate', models.DateField()),
                ('status', models.CharField(choices=[(b'Seen', b'Seen'), (b'Unseen', b'Unseen')], max_length=30)),
                ('seenDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('holidayID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(choices=[(b'Approved', b'Approved'), (b'Declined', b'Declined')], max_length=30)),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
        migrations.CreateModel(
            name='staffAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'Seen', b'Seen'), (b'Unseen', b'Unseen')], max_length=30)),
                ('alertID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.alerts')),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'db_table': 'staffAlerts',
            },
        ),
        migrations.AddField(
            model_name='alerts',
            name='fromStaff',
            field=models.ManyToManyField(related_name='_alerts_fromStaff_+', through='accounts.staffAlerts', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.holidays'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.projects'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='staff',
            field=models.ManyToManyField(blank=True, to='accounts.profile'),
        ),
    ]
