# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20170107_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='status',
        ),
    ]
