# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_alerts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='fromStaff',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='project',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffalerts',
            name='alertID',
        ),
        migrations.RemoveField(
            model_name='staffalerts',
            name='staffID',
        ),
        migrations.DeleteModel(
            name='alerts',
        ),
        migrations.DeleteModel(
            name='staffAlerts',
        ),
    ]
